### ISSUE TITLE
<i></i> and <b></b> tags don't work

### ISSUE THREAD

**Issue by xvazquezc** [elipapa/markdown-cv#18]
Hi there,

I'm trying to use jekyll-scholar to automate the bibliography section and I found out that when generated, the HTML tags `<i></i>` and `<b></b>` are there but are never displayed in the screen. I tested in both Firefox and Chrome in case it was an issue with the browser but the result is the same.

This also happens if I write literal HTML tags in the `index.md`, they appear in the source code of the HTML but they are not rendered in the screen.

Any idea why this could be?

Thank you in advance,
Xabi

PS: this is the link to the jekyll-scholar issue https://github.com/inukshuk/jekyll-scholar/issues/242

**Comment by elipapa** [comment]
you should specify a styling for `i` and `b` elements in the CSS file you use. 
All styles are cleared at the top of the default CSS, and no italic or bold tag is specified.
